-- TerraMind Database Schema for Supabase

-- Users table is managed by Supabase Auth, but you can add a public profile table.
-- This table will be automatically populated with a trigger on the auth.users table.
create table public.users (
  id uuid not null references auth.users on delete cascade,
  full_name text,
  avatar_url text,
  role text default 'user',
  primary key (id)
);

-- Land Plots table
create table public.land_plots (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users on delete cascade not null,
  name text not null,
  latitude numeric(10, 8) not null,
  longitude numeric(11, 8) not null,
  area_hectares numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Land Analytics table
create table public.land_analytics (
  id bigint generated by default as identity primary key,
  plot_id bigint references public.land_plots on delete cascade not null,
  ndvi numeric(5, 4),
  evi numeric(5, 4),
  soil_quality_score numeric(5, 2),
  analysis_date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Recommendations table
create table public.recommendations (
  id bigint generated by default as identity primary key,
  plot_id bigint references public.land_plots on delete cascade not null,
  crop_name text not null,
  reason text,
  recommendation_score numeric(3, 2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) for all tables
alter table public.users enable row level security;
alter table public.land_plots enable row level security;
alter table public.land_analytics enable row level security;
alter table public.recommendations enable row level security;

-- Add RLS policies here to restrict access, e.g.,
-- create policy "Users can only see their own plots." on land_plots for select using (auth.uid() = user_id);